library(tseries)
tb<-ts(read.csv("tb.csv",header= T),frequency=12, start=c(2011,1))
tb
plot.ts(tb)
acf(tb)
pacf(tb)
summary(tb)
library(moments)
skewness(tb)
kurtosis(tb)
jarque.bera.test(tb)
adf.test(tb, alternative = "stationary")
library(ggplot2)
library(forecast)
library(lmtest)
##Seasonal arima model##
plot.ts(diff(tb), ylab="First differenced tb frequency", xlab="Year", main="Differenced Time Plot of TB (d = 1)")
acf(diff(tb),lag.max = 24, main="Correlogram Plot of TB series (d = 1)")
pacf(diff(tb),lag.max = 120, main="Correlogram Plot of TB series (d = 1)")
adf.test(diff(tb), alternative = "stationary")
auto1 <- auto.arima(diff(tb),max.p = 10,max.q = 10,stationary = TRUE,stepwise=FALSE,approx=TRUE,seasonal = TRUE);summary(auto1)
coeftest(auto1)
fit_arima1 <- arima(tb,order=c(1,1,3),seasonal = list(order = c(1, 1, 1), period = 12));summary(fit_arima1)
coeftest(fit_arima1); BIC(fit_arima1)
fit_arima2 <- arima(tb,order=c(4,1,1),seasonal = list(order = c(1, 1, 1), period = 12));summary(fit_arima2)
coeftest(fit_arima2); BIC(fit_arima2)
fit_arima3 <- arima(tb,order=c(2,1,2),seasonal = list(order = c(1, 1, 2), period = 12));summary(fit_arima3)
coeftest(fit_arima3); BIC(fit_arima3)
fit_arima4 <- arima(tb,order=c(1,1,1),seasonal = list(order = c(1, 1, 1), period = 12));summary(fit_arima4)#Best Model
coeftest(fit_arima4); BIC(fit_arima4)
fit_arima5 <- arima(tb,order=c(2,1,1),seasonal = list(order = c(1, 1, 0), period = 12));summary(fit_arima5)
coeftest(fit_arima5); BIC(fit_arima5)
fit_arima6 <- arima(tb,order=c(1,1,1),seasonal = list(order = c(1, 1, 0), period = 12));summary(fit_arima6)
coeftest(fit_arima6); BIC(fit_arima6)
tsdiag(fit_arima4,18)
Box.test(resid(fit_arima4))
jarque.bera.test(resid(fit_arima4))
shapiro.test((resid(fit_arima4)))
forecast(fit_arima4, h=48)
plot(forecast(fit_arima4, h=48))
accuracy(forecast(fit_arima4, h=48))
